// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATleN_bCx8rJOMMbEGeBu9A4ZcIwcBmWU',
    appId: '1:159653812651:web:dd7bb3d64a56594105daee',
    messagingSenderId: '159653812651',
    projectId: 'realtime-chat-app-c5d26',
    authDomain: 'realtime-chat-app-c5d26.firebaseapp.com',
    storageBucket: 'realtime-chat-app-c5d26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgwQelSYXjCYK-lWWAz-hT7uC3BnF97z4',
    appId: '1:159653812651:android:908fcf5041ef49e005daee',
    messagingSenderId: '159653812651',
    projectId: 'realtime-chat-app-c5d26',
    storageBucket: 'realtime-chat-app-c5d26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB48sGpeTdkzLZaJisz0MGEyD1ezjjmKI',
    appId: '1:159653812651:ios:72c6fe4dd24810eb05daee',
    messagingSenderId: '159653812651',
    projectId: 'realtime-chat-app-c5d26',
    storageBucket: 'realtime-chat-app-c5d26.firebasestorage.app',
    iosBundleId: 'com.example.realtimeChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB48sGpeTdkzLZaJisz0MGEyD1ezjjmKI',
    appId: '1:159653812651:ios:72c6fe4dd24810eb05daee',
    messagingSenderId: '159653812651',
    projectId: 'realtime-chat-app-c5d26',
    storageBucket: 'realtime-chat-app-c5d26.firebasestorage.app',
    iosBundleId: 'com.example.realtimeChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATleN_bCx8rJOMMbEGeBu9A4ZcIwcBmWU',
    appId: '1:159653812651:web:203594b6f4d6992f05daee',
    messagingSenderId: '159653812651',
    projectId: 'realtime-chat-app-c5d26',
    authDomain: 'realtime-chat-app-c5d26.firebaseapp.com',
    storageBucket: 'realtime-chat-app-c5d26.firebasestorage.app',
  );
}
